# Cloud Build: build image and deploy to Cloud Run with GOOGLE_API_KEY
# Run: gcloud builds submit --config=cloudbuild.yaml --substitutions=_GOOGLE_API_KEY="$(grep '^GOOGLE_API_KEY=' .env | cut -d= -f2)"
# Or use deploy.ps1 / deploy.sh which pass the key automatically.

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: resume-rag
  _GOOGLE_API_KEY: ''  # Required; pass via --substitutions or use deploy script

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - '--image=gcr.io/${PROJECT_ID}/${_SERVICE_NAME}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=4Gi'
      - '--timeout=300'
      - '--min-instances=1'
      - '--set-env-vars=GOOGLE_API_KEY=${_GOOGLE_API_KEY}'

images:
  - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}'
